### ISSUE TITLE
Needed explanation

### ISSUE THREAD

**Issue by bramhechatejas** [danielpowney/my-chatbot#12]
Hi @danielpowney 

I didn't understand the meaning of what you have stated here. I guess, following update is old one only. Earlier too we were able to enable or disable these functionalities through option page. Will you please let us know if it is something new? 

**Added filters to modify the access token, enable welcome event, messaging platform, session id and show time options. This allows you to have different chatbots on different pages for example.**

Thanks,

**Comment by danielpowney** [comment]
I've simply added a WordPress filter so that you can modify some of the chatbot settings. So in theory, you could use an access token on one page and another on a different page. To do this, you would need to write some custom code to hook into the WordPress filter. See WordPress codex for [add_filter()](https://developer.wordpress.org/reference/functions/add_filter/) function.

**Comment by bramhechatejas** [comment]
Yeah okay, but may I know where have you added filters in my-chatbot plugin?
