### ISSUE TITLE
Rich messages

### ISSUE THREAD

**Issue by swellart** [danielpowney/my-chatbot#5]
Hi Daniel,
What should be done on Api ai side to have rich messages? 
Best regards
Valeriy

**Comment by danielpowney** [comment]
Hi Valeriy,

Add a response message content for a particular messaging platform such as Facebook Messenger which supports rich messages (e.g. Quick Replies or Image Response). Then in the plugin settings, set the messaging platform to Facebook Messenger so that the chatbot assumes the appearance of Facebook Messenger. 

Cheers,
Daniel

**Comment by swellart** [comment]
Thank you Daniel, it works!
Do you plan to add support for FB cards?
Valeriy

**Comment by swellart** [comment]
Hi Daniel,
one questions:
- what is the right method to send active link to plugin? When I send it as html (I mean in <a> tag) - it’s OK I see on WP page active link. But my API AI agent also connected  to FB Messenger and there I see  html code which is not good.
Best regards
Valeriy
